### PR TITLE
feat: add hard constraints on log scale and zero scale

### PR DESCRIPTION
**Pull request by JunranY**
for #791.
there is already a hard constraint for not using log with zero or negative values, here are the additional things I did: 
- added a hard constraint to make sure not to recommend log scale when extent includes zero
- To avoid redundant recommendation, I added a hard constraint to not recommend zero scale when extent includes zero
- added the facts about data schema to the query because previously the min and max are not both included
- updated the "revising soft constraints" example to cooperate the above change

### CODE REVIEW

**Review by domoritz — APPROVED** [review]
Thank you! 

> To avoid redundant recommendation, I added a hard constraint to not recommend zero scale when extent includes zero

I don't get this. I think it should be possible to specify `zero: true` on a scale even if the data already includes zero. This is actually a common case, I would think.

**Comment by JunranY** [comment]
I thought the definition of `zero: true` is "scale starts with 0" (as in the description), which means if the extent spans across 0 there is no way the scale is starting with 0.

**Comment by domoritz** [comment]
Hmm, I was going off of Vega which says "Boolean flag indicating if the scale domain should include zero.". We could rewrite the comment here or leave the current comment and accept your changes (probably the easiest option). 

Alternatively, we can just remove the flag and make it so that Draco can extend the domain for a scale to include zero but that's a bit more work.

**Comment by domoritz** [comment]
we decided
* zero should be an indicator to the scale domain computation to include zero (in addition to unioning the domains from all the fields that use the scale). 
* zero should have some soft-constraint cost
* not including zero for bar or area charts should have a higher cost

**Comment by JunranY** [comment]
I just realized that all of these are already implemented in: 
- `hard(bar_area_without_zero)`: Bar and area mark requires scale of continuous to start at zero. 
- `soft(continuous_not_zero)`: Prefer to include zero for continuous (binned doesn't need zero). 
- `soft(cross_zero)`: Prefer not to include zero as baseline when the range of data crosses zero. 

I'm thinking about 1) adding a constraint to allow zero only for quantitative scale (i.e. linear), 2)adjust the example in doc accordingly

**Comment by domoritz** [comment]
Sounds good. Let's be careful with terminology since a log scale could be considered quantitative as well.

**Review by domoritz — APPROVED** [review]

**Pull request merged**
