### PR TITLE
docs: no default value expansion

### PR DESCRIPTION
**Pull request by peter-gy**
### Goals

- Disable the expansion of default values in docstrings
- Fix the looks of the [Draco Class Documentation section](https://dig.cmu.edu/draco2/api/draco.html#class-documentation)

_Users_petergy_Coding_OpenSourceProjects_draco2_docs__build_html_api_draco html

### Notes

 - Found a solution which is the cleanest one imho: there is an [official `autodoc` config](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_preserve_defaults) for this

### CODE REVIEW

**Comment by peter-gy** [comment]
The GitHub workflow fails at [step 6](https://github.com/cmudig/draco2/runs/7425525058?check_suite_focus=true#step:9:7), however, the tests succeed for me locally.

```
Run poetry run pytest --cov=./ --cov-report=xml draco
Creating virtualenv draco-2B3FyYM-py3.8 in /home/runner/.virtualenvs
```

I assume that the failure is caused by the fact that no cached virtualenv is found by the time `poetry run pytest --cov=./ --cov-report=xml draco` gets executed, hence, `pytest` is not available for running the tests.

However, this problem is most probably not related to the changes I introduced in this PR.

**Comment by domoritz** [comment]
I tried restarting the builds and they still fail. I haven't seen this before.

**Comment by peter-gy** [comment]
The GitHub action fix I proposed handles the installation of `poetry` and the package caching via `actions/setup-python@v4`, as described in [its docs](https://github.com/actions/setup-python#caching-packages-dependencies). Before considering accepting this change, please run the workflow manually once again to make sure that the caching works as expected. (It works in my fork)

**Comment by domoritz** [comment]
Hmm, now I don't see any of the methods documented at https://dig.cmu.edu/draco2/api/draco.html. Do you know how we can add it back?

**Comment by peter-gy** [comment]
I actually don't recall that any of the methods have been documented in the previous version(s), but sure, I can take a look at it.

**Pull request merged**
