### PR TITLE
Section Stacking and Type checks for hard.lp

### PR DESCRIPTION
**Pull request by Zehua-Zeng**
I finished the hard constraints in section stacking and type checks. 
Somehow I couldn't figure out why two tests are failing. Let me know what you think. Thank you!

### CODE REVIEW

**Comment by domoritz** [comment]
Great. Please make sure the tests pass.

**Comment by domoritz** [comment]
Please update after https://github.com/cmudig/draco2/pull/194 is merged

**Comment by domoritz** [comment]
I converted this pull request to a draft. Please mark as ready when it's ready.

**Comment by Zehua-Zeng** [comment]
This pull request has too many constraints to review, I am separating this into multiple ones.

**Pull request closed without merging**
